export const LOCATION_GET_DIRECTION_REQUEST = "LOCATION_GET_DIRECTION_REQUEST";
export const LOCATION_GET_DIRECTION_SUCCESS = "LOCATION_GET_DIRECTION_SUCCESS";
export const LOCATION_GET_DIRECTION_FAIL = "LOCATION_GET_DIRECTION_FAIL";
